version: 2.1

parameters:
  run_by_api:
    type: boolean
    default: false
  class_size:
    type: string
    default: large
  zuid:
    type: string
    default: CIRCLE_PROJECT_USERNAME
  zuidq:
    type: string
    default: "<@$COMMITTER_USER_ID>"

jobs:
  regular:
    docker:
      - image: circleci/node:fermium
    steps:
      - checkout
      - run: echo `export TEST_THIS=Zach' >> $BASH_ENV
      - run: 
          command: |
            source $BASH_ENV
            echo $TEST_THIS


  # api-job:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - checkout
  #     - run: echo "I was run by API"

workflows:
  normal:
    jobs:
      - regular

  # api-workflow:
  #   when: << pipeline.parameters.run_by_api >> # Add condition to execute this workflow when condition-workflow is equal to true
  #   jobs:
  #     - api-job