version: 2.1

# orbs:
#   python: circleci/python@1.4.0

parameters:
  run_by_api:
    type: boolean
    default: false
  class_size:
    type: string
    default: large
  zuid:
    type: string
    default: CIRCLE_PROJECT_USERNAME
  zuidq:
    type: string
    default: "<@$COMMITTER_USER_ID>"

jobs:
  regular:
    # docker:
    #   - image: cimg/ruby:3.0.2-browsers
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: node -v
      - run: sudo apt-get install cloud-utils
      - run: ec2metadata --instance-id
      # - python/install-packages


  # api-job:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - checkout
  #     - run: echo "I was run by API"


workflows:
  normal:
    jobs:
      - regular

  # api-workflow:
  #   when: << pipeline.parameters.run_by_api >> # Add condition to execute this workflow when condition-workflow is equal to true
  #   jobs:
  #     - api-job
