version: 2.1

parameters:
  author:
    type: string
    default: "not_username"

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.6
      - run:
          name: "Install ruby"
          command: gem install bundler  && bundle install  

workflows:
  continue_workflow:
    when: 
      and:
        - not: 
            equal: [ "rbi-bot", << pipeline.parameters.author >> ]
    jobs:
     - build

# VS Code Extension Version: 1.5.1