version: 2.1

defaults: &defaults

orbs:
  aws-cli: circleci/aws-cli@3.1.4

parameters:
  author:
    type: string
    default: "not_username"

jobs:
  test:
    docker:
      - image: cimg/ruby:2.7.6
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: 'build test container'
          command: |
            gem list bundler ; 
            echo "######################" ;
            gem install bundler:2.0.0.pre.3 --default ;
            echo "######################" ;
            gem list bundler ;
            echo "######################" ;
            bundle -v ;
            echo "######################" ;
            bundle install --path .bundle ;

workflows:
  test:
    jobs:
      - test

# VS Code Extension Version: 1.5.1