version: 2.1

defaults: &defaults

orbs:
  aws-cli: circleci/aws-cli@3.1.4

parameters:
  author:
    type: string
    default: "not_username"

jobs:
  test:
    machine:
      image: "ubuntu-2004:current"
      docker_layer_caching: true
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: 'build test container'
          command: docker build . -t my-img
      - run:
          name: "start docker-compose"
          command: docker-compose up -d
      - run:
          name: "run tests"
          command: docker run -t --network=$(docker network ls | grep default | awk '{print $2}') my-img

workflows:
  test:
    jobs:
      - test

# VS Code Extension Version: 1.5.1