version: 2.1

defaults: &defaults

orbs:
  aws-cli: circleci/aws-cli@3.1.4
  newman: postman/newman@1.0.0
  android: circleci/android@2.1.2
  orby: orb-space/orb-project@1.0.4

parameters:
  author:
    type: string
    default: "not_username"
  branchyy:
    type: string
    default: << pipeline.git.branch >>


jobs:
  test:
    docker:
      - image: cimg/node:17.1.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    parameters:
      branchy:
        type: string
        default: "<< pipeline.git.branch >>"
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - run: docker ps
  test_windows:
    machine:
      image: 'windows-server-2019-vs2019:2023.08.2'
    steps:
      - run:
          name: Download WiX Toolset 
          command: |
            $url = "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe"
            $file = "$pwd\wix311.exe"
            $wc = New-Object System.Net.WebClient
            $wc.DownloadFile( $url, $file );
            Start-Process -Wait -FilePath "wix311.exe" -Argument "/silent" -PassThru
#       - run: echo << pipeline.id >>
#       - run: echo 'export PIPELINE_ID=<< pipeline.id >>' >> "$BASH_ENV"
#       - run: echo $PIPELINE_ID
# #      - run: python3 fail.py
#       - run: 
#           name: Rerun Workflow for Failed tests
#           command: |
#             echo 'export PIPELINE_ID=<< pipeline.id >>' >> "$BASH_ENV"
#             python3 rerun-failed.py
#           when: on_fail
#       - run: echo << pipeline.parameters.branchyy >>
      # - orby/greet:
      #     to: <<pipeline.git.branch>>
  # build:
  #   docker:
  #     - image: cimg/node:19.9.0
  #   steps:
  #     - checkout
  #     - run: 
  #         command: |
  #           sudo apt-get update
  #           sudo apt-get install curl
  #           curl --version
  #     - run: curl --version


workflows:
  work-it-flow:
    jobs:
      - test
      - test_windows
      # - build

# VS Code Extensi son Version: 1.5.1