version: 2.1

parameters:
  testParam:
    type: string
    default: "hello"

jobs:
  build:
    docker:
      - image: cimg/base:2022.12
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'

# VS Code Extension Version: 1.4.0