version: 2.1

defaults: &defaults

orbs:
  aws-cli: circleci/aws-cli@3.1.4

jobs:
  test:
    machine:
      image: "ubuntu-2004:current"
      docker_layer_caching: true
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: 'build test container'
          command: docker build . -t job_runner:test
      - run:
          name: "start docker-compose"
          command: docker-compose up -d
      - run:
          name: "run tests"
          command: docker run -t --network=$(docker network ls | grep default | awk '{print $2}') job_runner:test

workflows:
  version: 2
  test:
    jobs:
      - test:
          context:
            - PagerDuty
