version: 2.1

defaults: &defaults

orbs:
  aws-cli: circleci/aws-cli@3.1.4
  newman: postman/newman@1.0.0
  android: circleci/android@2.1.2

parameters:
  author:
    type: string
    default: "not_username"

jobs:
  test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2022.08.1
    steps:
      - checkout
      - run: echo << pipeline.id >>
      - run: 
          command: |
            echo 'export PIPELINE_ID="<< pipeline.id >>"' >> "$BASH_ENV"
            echo ${PIPELINE_ID}
      - run: python3 rerun-failed.py
  build:
    docker:
      - image: cimg/node:19.9.0
    steps:
      - checkout
      - run: 
          command: |
            sudo apt-get update
            sudo apt-get install curl
            curl --version
      - run: curl --version


workflows:
  test:
    jobs:
      - test
      - build

# VS Code Extensi son Version: 1.5.1