version: 2.1

parameters:
  testParam:
    type: string
    default: "not_hudcode"

jobs:
  build:
    docker:
      - image: cimg/base:2022.12
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'

workflows:
  continue_workflow:
    when: 
      and:
        - equal: [ "hud-code", << pipeline.parameters.testParam >> ]
    jobs:
     - build

# VS Code Extension Version: 1.4.0