version: 2.1

defaults: &defaults

orbs:
  aws-cli: circleci/aws-cli@3.1.4
  newman: postman/newman@1.0.0

parameters:
  author:
    type: string
    default: "not_username"

jobs:
  test:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run: npm init
      - run: yarn version
      - run: curl -v
  build:
    docker:
      - image: cimg/node:19.9.0
    steps:
      - checkout
      - run: node --version
      - run: npm init
      - run: yarn version

workflows:
  test:
    jobs:
      - test
      - build

# VS Code Extension Version: 1.5.1