version: 2.1

defaults: &defaults

orbs:
  aws-cli: circleci/aws-cli@3.1.4
  newman: postman/newman@1.0.0
  android: circleci/android@2.1.2
  orby: orb-space/orb-project@1.0.4

parameters:
  author:
    type: string
    default: "not_username"
  branchyy:
    type: boolean
    default: false


jobs:
  test_path_filtering:
    docker:
      - image: cimg/node:17.1.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - run: echo << pipeline.parameters.branchyy >>

  test_machine:
    machine: 
      image: ubuntu-2204:2023.10.1
    steps:
      - run: echo hello~

#       - run: echo << pipeline.id >>
#       - run: echo 'export PIPELINE_ID=<< pipeline.id >>' >> "$BASH_ENV"
#       - run: echo $PIPELINE_ID
# #      - run: python3 fail.py
#       - run: 
#           name: Rerun Workflow for Failed tests
#           command: |
#             echo 'export PIPELINE_ID=<< pipeline.id >>' >> "$BASH_ENV"
#             python3 rerun-failed.py
#           when: on_fail
#       - run: echo << pipeline.parameters.branchyy >>
      # - orby/greet:
      #     to: <<pipeline.git.branch>>
  # build:
  #   docker:
  #     - image: cimg/node:19.9.0
  #   steps:
  #     - checkout
  #     - run: 
  #         command: |
  #           sudo apt-get update
  #           sudo apt-get install curl
  #           curl --version
  #     - run: curl --version


workflows:
  work-it-flow:
    jobs:
      - test_path_filtering
      - test_machine

# VS Code Extensi son Version: 1.5.1