version: 2.1

parameters:
  author:
    type: string
    default: "not_username"

jobs:
  build:
    docker:
      - image: cimg/base:2022.12
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            echo << pipeline.parameters.author >>

workflows:
  continue_workflow:
    when: 
      and:
        - not: 
            equal: [ "hud-code", << pipeline.parameters.author >> ]
    jobs:
     - build

# VS Code Extension Version: 1.4.0