version: 2.1

parameters:
  author:
    type: string
    default: "not_username"

jobs:
  build:
    docker:
      - image: cimg/base:2022.12
    steps:
      - run:
          command: |
            echo "1000" > CACHE_VERSION
            date +%Y-week-%U > CACHE_WEEKNUMBER
          name: Create Files to checksum for cache keys

workflows:
  continue_workflow:
    when: 
      and:
        - not: 
            equal: [ "rbi-bot", << pipeline.parameters.author >> ]
    jobs:
     - build

# VS Code Extension Version: 1.4.0