version: 2.1

defaults: &defaults

orbs:
  aws-cli: circleci/aws-cli@3.1.4
  newman: postman/newman@1.0.0

parameters:
  author:
    type: string
    default: "not_username"

jobs:
  test:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run: 
          command: |
          apt-get -y update
          apt-get -y install curl
          curl --version
  # build:
  #   docker:
  #     - image: cimg/node:19.9.0
  #   steps:
  #     - checkout


workflows:
  test:
    jobs:
      - test
      # - build

# VS Code Extension Version: 1.5.1